server.port = 8080
$SERVER["socket"] == "0.0.0.0:8080" { }
$SERVER["socket"] == "[::]:8080" {
    server.use-ipv6 = "enable"
}

server.modules += ( "mod_alias", "mod_cgi" )
server.document-root = "/var/www/localhost/htdocs"
server.max-keep-alive-requests = 1
server.max-keep-alive-idle = 4

server.username = "unbound"
server.groupname = "unbound"

alias.url += ( "/stats" => "/usr/local/cgi-bin/stats.cgi" )

$HTTP["url"] =~ "^/stats$" {
    cgi.assign = ( "" => "" )
    mimetype.assign = ( ".cgi" => "text/plain" )
}
