# Unbound conf - 'https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html'
server:
  # Log only errors and display human-readable timestamps
  verbosity: 0
  log-time-ascii: yes

  # Listen on all addresses on all interfaces, detect the source interface on UDP queries and copy them to replies
  #interface-automatic: yes

  # Access treatment of incoming queries from their originating IP address
  access-control: 0.0.0.0 allow
  access-control: ::1 allow
  port: 53

  # Ensure privacy of local IP ranges
  private-address: 192.168.0.0/16
  private-address: 169.254.0.0/16
  private-address: 172.16.0.0/12
  private-address: 10.0.0.0/8
  private-address: fd00::/8
  private-address: fe80::/10

  # Enable IPv6 support if used
  do-ip6: yes
  do-ip4: yes
  do-udp: yes
  do-tcp: yes

  # Prefer IPv4. You want to leave this to no unless you have native IPv6
  prefer-ip6: no

  # For this setup, the default package dnssec-root package is installed. Unbound will find the root list automatically
  #root-hints: '/etc/unbound/root.hints'

  # Reduce EDNS reassembly buffer size. Limit DNS messages sent over UDP to a size that will not trigger fragmentation on typical network links
  edns-buffer-size: 1464

  # Perform prefetching of close to expired message cache entries
  prefetch: yes
  prefetch-key: yes

  # Hide DNS Server info
  hide-identity: yes
  hide-version: yes

  # Require DNSSEC data for trust-anchored zones, if such data is absent, the zone becomes BOGUS
  harden-dnssec-stripped: yes
  harden-referral-path: no

  # Don't use Capitalization randomization as it is known to cause DNSSEC issues sometimes
  use-caps-for-id: no

  # Turning this option off may avoid some validation failure
  harden-algo-downgrade: no

  # Unbound attempts to serve old responses from cache with an expired TTL
  serve-expired: yes
  serve-expired-ttl: 3600

  # Other options set by default
  qname-minimisation: yes
  aggressive-nsec: yes
  rrset-roundrobin: yes

  target-fetch-policy: '3 2 1 1 1'
  unwanted-reply-threshold: 10000000

  # Enable extended statistics
  extended-statistics: yes
  # Set to yes if the monitoring tool requires it
  statistics-cumulative: no

# Set up Remote Control to enable the unbound-control command - usefull for statistics
remote-control:
  control-enable: yes
  # Disables the use of TLS for localhost
  control-use-cert: no
